### ISSUE TITLE
Package failing to install when running model

### ISSUE THREAD

**Issue by spoonerf** [Urban-Analytics/rampuaR#11]
R[write to console]: Downloading GitHub repo Urban-Analytics/rampuaR@HEAD

   checking for file ‘/private/var/folders/yc/bkg2k6pj6td2tpkj64v1yvbr0000gn/T/Rtmpku7w21/remotesfe287160c574/Urban-Analytics-rampu✔  checking for file ‘/private/var/folders/yc/bkg2k6pj6td2tpkj64v1yvbr0000gn/T/Rtmpku7w21/remotesfe287160c574/Urban-Analytics-rampuaR-a37b527/DESCRIPTION’ (406ms)
─  preparing ‘rampuaR’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rampuaR_2.0.0.tar.gz’
   
* installing *source* package ‘rampuaR’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: object ‘is.factor.ff’ is not exported by 'namespace:ff'
Execution halted
ERROR: lazy loading failed for package ‘rampuaR’

**Comment by spoonerf** [comment]
Seems to be to do with a bad update in either the RecordLinkage or ff package. Thinking it might be best to remove the google mobility functions as they aren't needed for the running of the model. I've removed them on my branch and the model is running properly again. What do you think @Sparrow0hawk ?

**Comment by Sparrow0hawk** [comment]
I will take a look at this.

How come the google mobility functions aren't needed for the running of the model?

**Comment by spoonerf** [comment]
Ah they may become useful further down the line - at the moment to invoke lockdown we read in a google mobility multiplier csv which is specific to Devon. These functions would allow this multiplier to be created on-the-fly for any region. I'm not sure if it would be better to have them elsewhere and just run once to create a csv for each region?

**Comment by Sparrow0hawk** [comment]
So every time you run the model from scratch you'll need these functions? 

If thats the case i'd recommend keeping them in rather than moving them to ad-hoc R functions on the fly within the RAMP-UA python workflow.

I will dig into this and see if I can work out whats causing this problem.

**Comment by spoonerf** [comment]
Currently the functions aren't used in the model at all. However, we should be moving towards a place where they would be used when running the model from scratch, so would be ideal to keep them in!

It does look as if the RecordLinkage package itself is running into problems on CRAN https://cran.r-project.org/web/checks/check_results_RecordLinkage.html which might be the source of the troubles?

**Comment by Sparrow0hawk** [comment]
Good spot this definitely looks the likely cause of our issues!

**Comment by Sparrow0hawk** [comment]
Appears to be a specific problem with the `ffbase` package after changes to `ff` package (https://github.com/edwindj/ffbase/issues/59)

**Comment by spoonerf** [comment]
@Sparrow0hawk Have changed the function (LevensteinSim) that required that required the RecordLinkage (depends on ff) package to stringsim from the stringdist package - hopefully less troublesome! Looks like the package is installing correctly again.
